DECLARE @NOME VARCHAR(200)
DECLARE @ENDERECO VARCHAR(MAX)

DECLARE CURSOR2 CURSOR FOR 
SELECT NOME, (ENDERECO_1 + ' ' + BAIRRO+ ' ' + CIDADE + ' ' + ESTADO + ' CEP: ' + CEP) ENDCOMPLETO FROM [dbo].[TABELA_DE_CLIENTES]
OPEN CURSOR2
FETCH NEXT FROM CURSOR2 INTO @NOME, @ENDERECO
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'Nome: '+ @NOME + ', Endereço: ' + @ENDERECO
	FETCH NEXT FROM CURSOR2 INTO @NOME, @ENDERECO
END

CLOSE CURSOR2
DEALLOCATE CURSOR2