SELECT * FROM [dbo].[VENDEDORES]

SELECT DBO.NumeroAleatorio(1,16)

DECLARE @V_INICIAL INT
DECLARE @V_FINAL INT
DECLARE @CONTADOR INT
DECLARE @VENDEDOR VARCHAR(5)
DECLARE @ALEATORIO INT

SET @V_INICIAL = 1
SET @CONTADOR = 1

SELECT @V_FINAL = COUNT(*) FROM VENDEDORES
SET @ALEATORIO = dbo.NumeroAleatorio(@V_INICIAL, @V_FINAL)

DECLARE CURSOR_V2_ALEATORIO CURSOR FOR SELECT MATRICULA FROM VENDEDORES
OPEN CURSOR_V2_ALEATORIO
FETCH NEXT FROM CURSOR_V2_ALEATORIO INTO @VENDEDOR 
WHILE @CONTADOR < @ALEATORIO
BEGIN

	FETCH NEXT FROM CURSOR_V2_ALEATORIO INTO @VENDEDOR
	SET @CONTADOR = @CONTADOR + 1
END
CLOSE CURSOR_V2_ALEATORIO
DEALLOCATE CURSOR_V2_ALEATORIO

SELECT @VENDEDOR, @ALEATORIO
SELECT * FROM VENDEDORES
