
SELECT * FROM TABELA_DE_CLIENTES
SELECT COUNT(*) FROM TABELA_DE_CLIENTES

SELECT DBO.NumeroAleatorio(1,16)

DECLARE @CLIENTE_ALEATORIO VARCHAR(12)
DECLARE @VAL_INICIAL INT, @VAL_FINAL INT, @ALEATORIO INT
DECLARE @CONTADOR INT
SET @VAL_INICIAL = 1
SET @CONTADOR = 1
SELECT @VAL_FINAL = COUNT(*) FROM TABELA_DE_CLIENTES
SET @ALEATORIO = DBO.NumeroAleatorio(@VAL_INICIAL, @VAL_FINAL)

DECLARE CURSOR_ALEATORIO CURSOR FOR SELECT CPF FROM TABELA_DE_CLIENTES
OPEN CURSOR_ALEATORIO
FETCH NEXT FROM CURSOR_ALEATORIO INTO @CLIENTE_ALEATORIO
WHILE @CONTADOR < @ALEATORIO
BEGIN
	
	FETCH NEXT FROM CURSOR_ALEATORIO INTO @CLIENTE_ALEATORIO
	SET @CONTADOR = @CONTADOR + 1

END
CLOSE CURSOR_ALEATORIO
DEALLOCATE CURSOR_ALEATORIO

SELECT @CLIENTE_ALEATORIO, @ALEATORIO
SELECT * FROM TABELA_DE_CLIENTES