DECLARE @FUNCIONARIOS VARCHAR(150)
DECLARE nomeFunc CURSOR FOR SELECT NOME FROM TABELA_DE_VENDEDORES
OPEN nomeFunc
FETCH NEXT FROM nomeFunc INTO @FUNCIONARIOS  WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'Nome: ' + @FUNCIONARIOS
	FETCH NEXT FROM nomeFunc INTO @FUNCIONARIOS
END

CLOSE nomeFunc
DEALLOCATE nomeFunc
