
DECLARE @LIMITE_MINIMO INT, @LIMITE_MAXIMO INT
DECLARE @TABELA_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR (200), [FATURAMENTO] FLOAT)
DECLARE @CONTADOR_NOTAS INT

SET @LIMITE_MINIMO = 1
SET @LIMITE_MAXIMO = 100000

SET NOCOUNT ON 
WHILE @LIMITE_MINIMO <= @LIMITE_MAXIMO
BEGIN
 SELECT @CONTADOR_NOTAS = COUNT(*) FROM [dbo].[ITENS_NOTAS_FISCAIS] WHERE NUMERO = @LIMITE_MINIMO
 IF @CONTADOR_NOTAS > 0
	BEGIN
		INSERT INTO @TABELA_NUMEROS (NUMERO, STATUS, FATURAMENTO)
		 VALUES (@LIMITE_MINIMO, 'É NOTA FISCAL', [dbo].[FaturamentoNota](@LIMITE_MINIMO))
	END
 ELSE
	BEGIN
		INSERT INTO @TABELA_NUMEROS (NUMERO, STATUS, FATURAMENTO)
		 VALUES (@LIMITE_MINIMO, 'NÃO É NOTA FISCAL', 0)
	END
 SET @LIMITE_MINIMO = @LIMITE_MINIMO + 1

END
SELECT * FROM @TABELA_NUMEROS ORDER BY NUMERO

SELECT MIN(NUMERO), MAX(NUMERO) FROM [dbo].[ITENS_NOTAS_FISCAIS]