
SELECT RAND()

-- VALOR MINIMO SEJA 100
-- VALOR MAXIMO SEJA 500

SELECT ROUND (((500 - 100 - 1) * RAND() +100), 0)
SELECT ROUND (((1000 - 1 - 1) * RAND() +1), 0)

CREATE FUNCTION NumeroAleatorio(@VAL_MIN INT, @VALOR_MAX INT)
RETURNS INT
AS
BEGIN
	DECLARE @ALEATORIO INT
	DECLARE @VALOR_ALEATORIO FLOAT
	SELECT @VALOR_ALEATORIO = RAND()
	SET @ALEATORIO = ROUND (((@VALOR_MAX - @VAL_MIN - 1) * @VALOR_ALEATORIO + @VAL_MIN), 0)
	RETURN @ALEATORIO
END;

CREATE VIEW VW_ALEATORIO AS SELECT RAND() AS VALOR_ALEATORIO
SELECT * FROM VW_ALEATORIO 


CREATE FUNCTION NumeroAleatorio(@VAL_MIN INT, @VALOR_MAX INT)
RETURNS INT
AS
BEGIN
	DECLARE @ALEATORIO INT
	DECLARE @VALOR_ALEATORIO FLOAT
	SELECT @VALOR_ALEATORIO = VALOR_ALEATORIO FROM VW_ALEATORIO
	SET @ALEATORIO = ROUND (((@VALOR_MAX - @VAL_MIN - 1) * @VALOR_ALEATORIO + @VAL_MIN), 0)
	RETURN @ALEATORIO
END;

SELECT dbo.[NumeroAleatorio](1,10)