SELECT TP.SABOR, SUM(INF.QUANTIDADE * INF.PRECO) AS FATURAMENTO
FROM [dbo].[TABELA_DE_PRODUTOS] AS TP
INNER JOIN [dbo].[ITENS_NOTAS_FISCAIS] AS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN [dbo].[NOTAS_FISCAIS] AS NF
ON NF.NUMERO = INF.NUMERO
WHERE NF.DATA_VENDA >= '2015-01-01' AND NF.DATA_VENDA <= '2015-12-31'
GROUP BY TP.SABOR

CREATE PROCEDURE faturamentoDepartamento (@DataInicial DATE, @DataFinal DATE)
AS
BEGIN
	DECLARE @DEPARTAMENTO TABLE (SABOR VARCHAR(20), DEPARTAMENTO VARCHAR(20))
	INSERT INTO @DEPARTAMENTO
	SELECT DISTINCT SABOR, 'FRUTAS Ñ CÍTRICAS' AS DEPARTAMENTO
	FROM [dbo].[TABELA_DE_PRODUTOS] WHERE
	SABOR IN ('Açai','Cereja','Cereja/Maça','Maça','Manga','Maracujá','Melância')
	UNION
	SELECT DISTINCT SABOR, 'FRUTRAS CÍTRICAS' AS DEPARTAMENTO
	FROM [dbo].[TABELA_DE_PRODUTOS] WHERE
	SABOR IN ('Laranja','Uva','Limão','Morango','Morango/Limão','Lima/Limão')

	SELECT DP.DEPARTAMENTO, SUM(INF.QUANTIDADE * INF.PRECO) AS FATURAMENTO
	FROM [dbo].[TABELA_DE_PRODUTOS] AS TP
	INNER JOIN [dbo].[ITENS_NOTAS_FISCAIS] AS INF
	ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
	INNER JOIN [dbo].[NOTAS_FISCAIS] NF
	ON NF.NUMERO = INF.NUMERO
	INNER JOIN @DEPARTAMENTO DP
	ON TP.SABOR = DP.SABOR
	WHERE NF.DATA_VENDA >= @DataInicial AND NF.DATA_VENDA <= @DataFinal
	GROUP BY DP.DEPARTAMENTO
END

EXEC faturamentoDepartamento '2015-01-01', '2016-01-15'