ALTER PROCEDURE retornaValoresFaturamentoQuantidade
@CPF AS VARCHAR(12), @ANO AS INT, @NUM_NOTAS AS INT OUTPUT, @FATURAMENTO AS FLOAT OUTPUT
AS
BEGIN
	SELECT @NUM_NOTAS = COUNT(*) FROM NOTAS_FISCAIS
	WHERE CPF = @CPF AND YEAR(DATA_VENDA) = @ANO

	SELECT @FATURAMENTO = SUM(INF.QUANTIDADE * INF.PRECO)
	FROM ITENS_NOTAS_FISCAIS INF
	INNER JOIN NOTAS_FISCAIS NF
	ON INF.NUMERO = NF.NUMERO
	WHERE NF.CPF = @CPF AND YEAR(NF.DATA_VENDA) = @ANO
END

DECLARE @NUM_NOTAS INT
DECLARE @FATURAMENTO FLOAT

SET @NUM_NOTAS = 0
SET @FATURAMENTO = 0

SELECT @NUM_NOTAS, @FATURAMENTO
EXEC retornaValoresFaturamentoQuantidade @CPF='19290992743', @ANO=2017, 
@NUM_NOTAS=@NUM_NOTAS OUTPUT, @FATURAMENTO=@FATURAMENTO OUTPUT

SELECT @NUM_NOTAS, @FATURAMENTO
