


	CREATE TRIGGER TG_CLIENTES_IDADE
	ON [dbo].[CLIENTES]
	AFTER INSERT, DELETE, UPDATE
	AS
	BEGIN
		UPDATE [CLIENTES] SET [IDADE] = 
    DATEDIFF(YEAR, [DATA_NASCIMENTO], GETDATE());

	END;

	SELECT [CPF], [IDADE], [DATA_NASCIMENTO], 
    DATEDIFF(YEAR, [DATA_NASCIMENTO], GETDATE()) 
FROM CLIENTES



CREATE TABLE TAB_CHECK
(ID INT NOT NULL,
NOME VARCHAR(50) NULL,
IDADE INT NULL,
CIDADE VARCHAR(50) NULL,
CONSTRAINT CHK_IDADE CHECK (IDADE >= 18));

INSERT INTO TAB_CHECK VALUES (1, 'João', 19, 'RJ');
INSERT INTO TAB_CHECK VALUES (3, 'Pedro', 4, 'SP');

CREATE TABLE TAB_CHECK2
(ID INT NOT NULL,
NOME VARCHAR(50) NULL,
IDADE INT NULL,
CIDADE VARCHAR(50) NULL,
CONSTRAINT CHK_IDADE2 CHECK ((IDADE >= 18 AND CIDADE = 'RJ') OR (IDADE >= 16 AND CIDADE = 'SP')));

INSERT INTO TAB_CHECK2 VALUES (1, 'João', 19, 'RJ');
INSERT INTO TAB_CHECK2 VALUES (3, 'Pedro', 17, 'SP');