CREATE TRIGGER TG_ITENS_VENDIDOS
ON [dbo].[TABELA_DE_ITENS_VENDIDOS]
  INSERT, UPDATE, DELETE
AS
BEGIN

DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT 
TV.DATA_VENDA,
SUM (TIV.QUANTIDADE * TIV.PRECO) AS TOTAL_VENDA
FROM TABELA_DE_VENDAS TV
INNER JOIN TABELA_DE_ITENS_VENDIDOS TIV
ON TV.NUMERO = TIV.NUMERO
GROUP BY
TV.DATA_VENDA

END;