/*--------------------------------------------------------------------------------------------*/
/*								AULA 06.1 - VENDAS VÁLIDAS									  */
/*--------------------------------------------------------------------------------------------*/
SELECT 
NF.CPF, 
CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS ANO_MES, 
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY
NF.CPF,
CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)

/*-----------------------------*/

SELECT
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.ANO_MES, TV.QUANTIDADE_TOTAL,
(
CASE WHEN 
TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS INVÁLIDAS' 
END
) AS RESULTADO
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT 
NF.CPF, 
CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS ANO_MES, 
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY
NF.CPF,
CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
) AS TV
ON
TV.CPF = TC.CPF
WHERE TV.ANO_MES = '2015-01'

/*--------------------------------------------------------------------------------------------*/
/*                         DESAFIO 06.2 - COMPLEMENTANDO O RELATÓRIO                          */
/*--------------------------------------------------------------------------------------------*/

SELECT
TC.CPF, 
TC.NOME, 
TC.VOLUME_DE_COMPRA, 
TV.ANO_MES, 
TV.QUANTIDADE_TOTAL, 
ROUND((1 - (TC.VOLUME_DE_COMPRA/TV.QUANTIDADE_TOTAL)) * 100, 2) AS PERCENTUAL,
(
CASE WHEN 
TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS INVÁLIDAS' 
END
) AS RESULTADO
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT 
NF.CPF, 
CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS ANO_MES, 
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY
NF.CPF,
CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
) AS TV
ON
TV.CPF = TC.CPF
WHERE TV.ANO_MES = '2015-01'
AND
TC.VOLUME_DE_COMPRA < TV.QUANTIDADE_TOTAL

/*--------------------------------------------------------------------------------------------*/
/*                            AULA 06.3 - VENDAS POR SABOR                                    */
/*--------------------------------------------------------------------------------------------*/

SELECT
TP.SABOR, 
YEAR(NF.DATA_VENDA) AS ANO,
SUM(INF.QUANTIDADE) AS VENDA_ANO
FROM
TABELA_DE_PRODUTOS TP
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN
NOTAS_FISCAIS NF
ON INF.NUMERO = NF.NUMERO
WHERE 
YEAR(NF.DATA_VENDA) = 2015 
GROUP BY
TP.SABOR, YEAR(NF.DATA_VENDA)
ORDER BY
SUM(INF.QUANTIDADE) DESC

--calcular o Total vendas
SELECT 
YEAR(NF.DATA_VENDA) AS ANO,
SUM(INF.QUANTIDADE) AS VENDA_TOTAL_ANO
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON
NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2015
GROUP BY
YEAR(NF.DATA_VENDA)

-------------------------------------------------------------------------------------------------------------------
--fazendo o Inner Join entre as duas query acima, retira-se sempre quando houver o "ORDER BY" de dentro de subquery
-------------------------------------------------------------------------------------------------------------------

SELECT
VS.SABOR, 
VA.ANO,
VS.VENDA_ANO,
VA.VENDA_TOTAL_ANO
FROM
(
SELECT
TP.SABOR, 
YEAR(NF.DATA_VENDA) AS ANO,
SUM(INF.QUANTIDADE) AS VENDA_ANO
FROM
TABELA_DE_PRODUTOS TP
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN
NOTAS_FISCAIS NF
ON INF.NUMERO = NF.NUMERO
WHERE 
YEAR(NF.DATA_VENDA) = 2015 
GROUP BY
TP.SABOR, YEAR(NF.DATA_VENDA)
) AS VS

INNER JOIN
(
SELECT 
YEAR(NF.DATA_VENDA) AS ANO,
SUM(INF.QUANTIDADE) AS VENDA_TOTAL_ANO
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON
NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2015
GROUP BY
YEAR(NF.DATA_VENDA)
) AS VA
ON 
VS.ANO = VA.ANO
ORDER BY 
VS.VENDA_ANO DESC

-------------------------------------------------------------------------------------------------------------------
--Criar coluna percentual e covnerter int para float e incluir com 2 casas decimais
-------------------------------------------------------------------------------------------------------------------

SELECT
VS.SABOR, 
VA.ANO,
VS.VENDA_ANO,
VA.VENDA_TOTAL_ANO,
ROUND((CONVERT(FLOAT, VS.VENDA_ANO)/CONVERT(FLOAT, VA.VENDA_TOTAL_ANO)) * 100, 2) AS PERCENTUAL
FROM
(
SELECT
TP.SABOR, 
YEAR(NF.DATA_VENDA) AS ANO,
SUM(INF.QUANTIDADE) AS VENDA_ANO
FROM
TABELA_DE_PRODUTOS TP
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN
NOTAS_FISCAIS NF
ON INF.NUMERO = NF.NUMERO
WHERE 
YEAR(NF.DATA_VENDA) = 2015 
GROUP BY
TP.SABOR, YEAR(NF.DATA_VENDA)
) AS VS

INNER JOIN
(
SELECT 
YEAR(NF.DATA_VENDA) AS ANO,
SUM(INF.QUANTIDADE) AS VENDA_TOTAL_ANO
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON
NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2015
GROUP BY
YEAR(NF.DATA_VENDA)
) AS VA
ON 
VS.ANO = VA.ANO
ORDER BY 
VS.VENDA_ANO DESC


/*--------------------------------------------------------------------------------------------*/
/*                          DESAFIO 06.4 - VENDAS PERCENTUAIS POR TAMANHO                     */
/*--------------------------------------------------------------------------------------------*/

SELECT
VS.TAMANHO, 
VA.ANO,
VS.VENDA_ANO,
VA.VENDA_TOTAL_ANO,
ROUND((CONVERT(FLOAT, VS.VENDA_ANO)/CONVERT(FLOAT, VA.VENDA_TOTAL_ANO)) * 100, 2) AS PERCENTUAL
FROM
(
SELECT
TP.TAMANHO, 
YEAR(NF.DATA_VENDA) AS ANO,
SUM(INF.QUANTIDADE) AS VENDA_ANO
FROM
TABELA_DE_PRODUTOS TP
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN
NOTAS_FISCAIS NF
ON INF.NUMERO = NF.NUMERO
WHERE 
YEAR(NF.DATA_VENDA) = 2015 
GROUP BY
TP.TAMANHO, YEAR(NF.DATA_VENDA)
) AS VS
INNER JOIN
(
SELECT 
YEAR(NF.DATA_VENDA) AS ANO,
SUM(INF.QUANTIDADE) AS VENDA_TOTAL_ANO
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON
NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2015
GROUP BY
YEAR(NF.DATA_VENDA)
) AS VA
ON 
VS.ANO = VA.ANO
ORDER BY 
VS.VENDA_ANO DESC
