/*AULA 05.2 - FUNÇÕES DE TEXTO*/
SELECT * FROM TABELA_DE_CLIENTES

--Função LOWER e UPPER
SELECT NOME, 
LOWER(NOME) AS NOME_MINUSCULO, 
UPPER(NOME) AS NOME_MAIUSCULO 
FROM TABELA_DE_CLIENTES

--Função CONCAT
SELECT NOME, CONCAT(ENDERECO_1, ' ', BAIRRO, ' ',CIDADE, ' ',ESTADO, ' - ', CEP) AS ENDERECO_COMPLETO
FROM TABELA_DE_CLIENTES
--pode substituir  a , por + para realizar a concatenação do texto;

--Função LEFT e RIGHT
SELECT NOME_DO_PRODUTO, LEFT(NOME_DO_PRODUTO, 3) AS TRE_PRIMEIROS_CHAR
FROM TABELA_DE_PRODUTOS

--Função REPLACE
SELECT TAMANHO, REPLACE((REPLACE(TAMANHO, 'Litros', 'L')), 'Litro', 'L') AS TAMANHO_MODIFICADO
FROM TABELA_DE_PRODUTOS

/*DESAFIO 05.4 - SEPARANDO NOME E SOBRENOME*/
SELECT NOME, SUBSTRING(NOME, 1, CHARINDEX(' ', NOME, 1))  AS PRIMEIRO_NOME
FROM TABELA_DE_CLIENTES;

/*AULA 05.5 - FUNÇÕES DE DATAS*/
SELECT GETDATE()
--somando 10 dias da data atual;
SELECT GETDATE() AS DATA_HOJE, DATEADD(DAY, 10, GETDATE()) AS DATA_DAQUI_10_DIAS
--48 dias atrás;
SELECT GETDATE() AS DATA_HOJE, DATEADD(DAY, -48, GETDATE()) AS DATA_48_DIAS_ATRAS
--Quantos dias se passarram desde o primeiro dia do ano
SELECT GETDATE() AS DATA_HOJE, DATEADD(DAY, -48, GETDATE()) AS DATA_48_DIAS_ATRAS, DATEDIFF (DAY,'2025-01-01', GETDATE()) AS DIAS_DESDE_INICIO_ANO
--Dia de Hoje
SELECT GETDATE() AS DATA_HOJE, DATEPART(DAY, GETDATE()) AS DIA_DE_HOJE
--Data válida ( 1 é valido e 0 ou erro 289 é que a data é inválida) 
SELECT ISDATE(DATETIMEFROMPARTS(2022,02,29,00,00,00,00))

/*DESAFIO 05.7 - DATA POR EXTENSO*/
SELECT NOME + ' nasceu em ' + 
DATENAME (WEEKDAY,DATA_DE_NASCIMENTO) + ',' +
DATENAME (DAY,DATA_DE_NASCIMENTO) + ' de ' +
DATENAME(MONTH, DATA_DE_NASCIMENTO) + ' de ' +
DATENAME(YEAR, DATA_DE_NASCIMENTO) AS DATA_EXTENSO
FROM TABELA_DE_CLIENTES;

/*AULA 05.8 - FUNÇÕES NUMÉRICAS*/
SELECT ROUND (3.433, 2) AS ARREDONDAMENTO, 
ROUND (3.437, 2) AS ARREDONDAMENTO, 
CEILING(3.433) AS MAIOR_NUM_INTEIRO, 
FLOOR(3.433) AS MESMO_NUM_INTEIRO,
POWER(12,2) AS ELEVADO,
EXP(3) AS EXPONENCIAL,
SQRT(300) AS RAIZ_QUADRADA,
ABS(10), ABS(-10)

/*DESAFIO 5.9 - FORMATO DO FATURAMENTO*/
SELECT YEAR(DATA_VENDA) AS ANO, FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) AS IMPOSTO
FROM NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA);

/*AULA 5.10 - FUNÇÕES DE CONVERSÃO*/
SELECT CONVERT(VARCHAR(19), GETDATE(), 121)

SELECT DATA_DE_NASCIMENTO, CONVERT(varchar(25), DATA_DE_NASCIMENTO, 121) AS D_NASC
FROM TABELA_DE_CLIENTES
--trocando a máscara para 106, exibirá a data de maneira diferente
SELECT DATA_DE_NASCIMENTO, CONVERT(varchar(25), DATA_DE_NASCIMENTO, 106) AS D_NASC
FROM TABELA_DE_CLIENTES

--Conversão de forma implícita
SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: ', PRECO_DE_LISTA) AS PRECO
FROM TABELA_DE_PRODUTOS

SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: ', CAST(PRECO_DE_LISTA AS varchar(10))) AS PRECO
FROM TABELA_DE_PRODUTOS

/*DESAFIO 5.11 - LISTANDO EXPRESSÃO NATURAL*/
SELECT TC.NOME, CONCAT('O cliente ', TC.NOME, ' comprou R$ ',
TRIM(STR(SUM(IT.QUANTIDADE * IT.PRECO) ,10,2)), ' no ano de ', YEAR(NF.DATA_VENDA), '.') AS VALOR
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS IT ON NF.NUMERO = IT.NUMERO
INNER JOIN TABELA_DE_CLIENTES AS TC ON NF.CPF = TC.CPF
WHERE YEAR(NF.DATA_VENDA) = '2016'
GROUP BY TC.NOME, YEAR(NF.DATA_VENDA);