/*AULA 01*/
SELECT COUNT(*) FROM TABELA_DE_CLIENTES;
SELECT COUNT(*) FROM TABELA_DE_PRODUTOS;
SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;
SELECT COUNT(*) FROM NOTAS_FISCAIS;
SELECT COUNT(*) FROM ITENS_NOTAS_FISCAIS;

/*AULA 02.1 - CONSULTA SIMPLES DE UMA TABELA*/
SELECT * FROM TABELA_DE_CLIENTES
SELECT NOME, CPF, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES
SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DE CLIENTES], BAIRRO, CIDADE FROM TABELA_DE_CLIENTES
SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DE CLIENTES], BAIRRO, CIDADE FROM TABELA_DE_CLIENTES TDC; /*No Alias da tabela suprime o AS;*/
SELECT TDC.CPF, TDC.NOME, TDC.BAIRRO FROM TABELA_DE_CLIENTES TDC;
SELECT TABELA_DE_CLIENTES.CPF, TABELA_DE_CLIENTES.NOME FROM TABELA_DE_CLIENTES;

/*AULA 02.3 - CONSULTA COM FILTRO*/
SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM TABELA_DE_PRODUTOS WHERE 1=1; /*Todos os resultados serão verdadeiros*/
SELECT * FROM TABELA_DE_PRODUTOS WHERE 1=0; /*Todos os resultados serão falsos*/
SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = '290478'; 
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja';
SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'Pet';

/*AULA 02.5 - FILTROS QUANTITATIVOS*/
SELECT * FROM TABELA_DE_CLIENTES; 
SELECT * FROM TABELA_DE_CLIENTES WHERE  IDADE > 20; 
SELECT * FROM TABELA_DE_CLIENTES WHERE  IDADE < 20; 
SELECT * FROM TABELA_DE_CLIENTES WHERE  IDADE <= 20; 
SELECT * FROM TABELA_DE_CLIENTES WHERE  IDADE < 18; 
SELECT * FROM TABELA_DE_CLIENTES WHERE  IDADE <> 18;
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '1995-11-14';
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO < '1995-11-14';
SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO >= 'Lapa';

/*AULA 02.7 - EXPRESSÕES LÓGICAS*/
SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' AND TAMANHO = '470 ml'
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR TAMANHO = '470 ml'
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' AND TAMANHO = '470 ml');
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' OR TAMANHO = '470 ml');

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'Manga' AND TAMANHO = '470 ml');
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT SABOR = 'Manga' AND TAMANHO = '470 ml';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' OR SABOR = 'Laranja' OR SABOR = 'Melancia';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('Manga','Laranja','Melancia');
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('Manga','Laranja','Melancia') AND TAMANHO = '1 Litro';

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro', 'Sao Paulo');
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro', 'Sao Paulo') AND IDADE >= 20;

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro', 'Sao Paulo') AND (IDADE >= 20 AND IDADE <= 25);
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro', 'Sao Paulo') AND (IDADE BETWEEN 20 AND 25);

/*AULA 02.11 - USANDO O LIKE*/
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('Lima/Limao', 'Morango/Limao');
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Limao%';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Maca%';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE 'Morango%';
SELECT * FROM TABELA_DE_PRODUTOS WHERE (SABOR LIKE 'Morango%') AND (EMBALAGEM = 'PET');

/*ATIVIDADE 02.11 - BUSCANDO CLIENTES*/
SELECT * FROM TABELA_DE_CLIENTES WHERE NOME LIKE '%Silva%';